# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config| 
  
  config.vm.box = "yussupov/firstVagrantBox"
  config.vm.box_version = "0.0.1"
  config.vm.hostname = "single"
  config.vm.box_url = "https://atlas.hashicorp.com/yussupov/boxes/firstVagrantBox"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.synced_folder  "..", "/custom_shared"
  
  config.vm.provider "virtualbox" do |vb|

	vb.memory = "1024"
	vb.cpus = 1
	vb.customize ["modifyvm", :id, "--cpuexecutioncap", "75"]
  end
  

   config.vm.provision "shell", inline: <<-SHELL
  
      sudo apt-get update
      sudo apt-get install -y apache2
	  
	  sudo yum -y install httpd
	  sudo yum -y install mariadb-server
	  sudo yum -y install php php-mysql
	  
	  sudo firewall-cmd --permanent --add-port=80/tcp
	  sudo firewall-cmd --reload

	  sudo systemctl start httpd
	  sudo systemctl enable httpd
	  sudo systemctl status httpd
	  
	  sudo systemctl start mariadb
	  sudo systemctl enable mariadb.service
	  
	  sudo chmod -R 777 /var/www/html
	  cat <<EOF | mysql
	  SET PASSWORD FOR 'root'@'localhost' = PASSWORD('secret');
	  DELETE FROM mysql.user WHERE User='';
	  FLUSH PRIVILEGES;
EOF
SHELL
   config.vm.provision "file", source: "index.php", destination: "/var/www/html/index.php"
end
